### ISSUE TITLE
No detection of argagg in cmake

### ISSUE THREAD

**Issue by OdyX** [blupi-games/planetblupi#1]
Hi there,

while trying to build Planet Blupi here, I fell on a compilation error where ```#include <argagg/argagg.hpp>``` fails if no such argagg.hpp (from https://github.com/vietjtnguyen/argagg) is available in the include paths. This should really be detected in CMake.

(Same goes for kitchensink by the way…)

Cheers,
  OdyX

**Comment by Skywalker13** [comment]
Yes, sure.. it needs to write find_package stuff for these dependencies.. like with iconv in the `cmake/` directory. I must investigate...

**Comment by Skywalker13** [comment]
It should be fine for both libs; it uses CMake via `find_library`
