### ISSUE TITLE
Add Arabic Translation

### ISSUE THREAD

**Issue by WindowsNinetyTen** [blupi-games/planetblupi#102]
Please Add an Arabic translation for this game. Thank you.

**Comment by Skywalker13** [comment]
I'm open to new translations but I need someone to translate. I can prepare text glyphs for non-latin translations if I'm sure that someone write all texts.

**Comment by Skywalker13** [comment]
See https://github.com/blupi-games/planetblupi/blob/master/README.translators.md for more details

**Comment by WindowsNinetyTen** [comment]
I'm trying to use the Hebrew file as a base for the Arabic (for Arabic is also written right-to-left), but I see just boxes when I view the file.

**Comment by WindowsNinetyTen** [comment]
I have begun work on the Arabic translation. But where can I find the hard-coded text in the source code?

**Comment by Skywalker13** [comment]
It uses PO format like described in <https://github.com/blupi-games/planetblupi/blob/master/README.translators.md>

The hard coded texts are extracted by xgettext. Do you need help about gettext / po stuff?

**Comment by WindowsNinetyTen** [comment]
Okay. I mean:
    if (locale == "en")
      lang = "English";
    else if (locale == "en_US")
      lang = "American english";
    else if (locale == "fr")
      lang = "Français";
    else if (locale == "de")
      lang = "Deutsch";
    else if (locale == "it")
      lang = "Italiano";
    else if (locale == "pl")
      lang = "Polski";
    else if (locale == "tr")
      lang = "Türkçe";
    else if (locale == "pt")
      lang = "Português";
    else if (locale == "he")
      lang = "עברית";

**Comment by Skywalker13** [comment]
<https://github.com/blupi-games/planetblupi/blob/master/src/event.cxx#L2789=>

**Comment by WindowsNinetyTen** [comment]
Thanks. Now, how do I provide/make the voices?

**Comment by WindowsNinetyTen** [comment]
I just finished translating. However, when I tested it, I just say boxes instead of Arabic characters.

**Comment by Skywalker13** [comment]
Yes you see boxes because the glyphs must be drawn for Arabic (it's just bitmaps). Thank you very much for the translations. I will prepare the font in the next days.

**Comment by WindowsNinetyTen** [comment]
You are most welcome. But how can I provide the voices? Do I use my voice and then the recordings get edited, for example?

**Comment by Skywalker13** [comment]
Yes, just use your voice (or someone else). After that the sound must be modified in order to sound like the original (french) voice.

**Comment by Skywalker13** [comment]
... low resolution for arabic fonts is challenging for me.. but I like the challenges

**Comment by WindowsNinetyTen** [comment]
I'm glad that you like it. I shall soon record the voices, but I don't know how to modify them to sound like the original voices. Speaking of which, the Arabic voices will be translated from the French ones.

**Comment by Skywalker13** [comment]
You can try this with Audacity:

![image](https://user-images.githubusercontent.com/397862/167026279-28dc4d24-bd78-4982-aa36-22265acd4323.png)

Keep default values excepted for **to** frequency  (put 882 for example)
![image](https://user-images.githubusercontent.com/397862/167026401-46aa8219-910a-475c-a740-e714db192086.png)

Try other values if necessary...

**Comment by WindowsNinetyTen** [comment]
[Planet Blupi Arabic Voices.zip](https://github.com/blupi-games/planetblupi/files/8636437/Planet.Blupi.Arabic.Voices.zip)

**Comment by Skywalker13** [comment]
Hello, Thank you

Maybe the frequency is a bit too high, it sounds metallic

From my side, I continue to work on the fonts (I don't have a lot of free time for that, but I have some progress...)

**Comment by WindowsNinetyTen** [comment]
Yeah, and the volume is also a bit too low

**Comment by WindowsNinetyTen** [comment]
Do you know any way that I could try to help with the fonts?

**Comment by Skywalker13** [comment]
I'm discovering that Arabic use ligatures everywhere and every time… it's difficult to integrate in planetblupi because I don't have real font here.

I have drawn the glyphs like that:
![image](https://user-images.githubusercontent.com/397862/167731386-88b76dfd-ccb1-41a2-974d-d5b20bfa3a01.png)

But it can't work because I'm just placing each bitmap at the right place according to the UTF8 code. I don't have a real font.. I don't have ligatures support.

The result in Planet Blupi is **very bad** (there are still some other bugs and bad widths, of course) :
![image](https://user-images.githubusercontent.com/397862/167731572-299d53d6-5328-44c1-a888-d10e97b66cc5.png)

But the major problem is that the characters as just put **side by side**...

It's impossible with the current impl. in planetblupi to do something like that:
![image](https://user-images.githubusercontent.com/397862/167731711-b505a9f7-7460-4e5a-be30-f703e7746613.png)


Maybe it's the time for me to drop all this old crappy stuff about the fonts in planetblupi, and replace it with SDL_TTF which supports properly all the very complex things with the fonts in all languages...

I must investigate more deeply

**Comment by WindowsNinetyTen** [comment]
Oh dear. I am sorry that you are having some trouble. Also, I just noticed a typo in the translation: ’ظلى’ should be ’على’.

**Comment by Skywalker13** [comment]
Hello, just for your information.. I need more time to (find) free time for SDL_ttf. I've not forgotten your precious Arabic translation.

**Comment by WindowsNinetyTen** [comment]
I understand. Thank you for letting me know. After all, I was thinking of revising the translation a little to make it as 1:1 as possible with the French version,

**Comment by Skywalker13** [comment]
I'm playing with SDL_ttf and RTL mode but the ligatures are not "ŵorking.. 😢  I must investigate ...

![image](https://user-images.githubusercontent.com/397862/178077450-6354ff4d-54f4-40a9-88d4-8ac59429a1e2.png)

**Comment by Skywalker13** [comment]
![image](https://user-images.githubusercontent.com/397862/178161365-e6826f95-b70d-4508-a546-754f20854418.png)

**Comment by WindowsNinetyTen** [comment]
Great! Thank you very much! I see that you've now got it right!

**Comment by Skywalker13** [comment]
Hello, sorry for the long delay..  I've still one problem with arabic (and hebrew by the way now that I use real fonts instead of sprites); it's when english words and numbers are mixed in the texts because it's reversed and it should not. Once I've fixed that, I can provide a release candidate.

**Comment by Skywalker13** [comment]
Hi, a part of the translation is missing (still using hebrew) for the mission 19.

![image](https://user-images.githubusercontent.com/397862/198899569-b5fe022f-7b3d-4769-b433-fbc64ffce058.png)

**Comment by WindowsNinetyTen** [comment]
Oh. I shall fix that as soon as posssible. I used a copy of the Hebrew file for I thought that it would be easier to derive the Arabic from that due to same writing direction.

**Comment by Skywalker13** [comment]
Yes no problem; my free time is limited too

**Comment by WindowsNinetyTen** [comment]
[arabic stories.zip](https://github.com/blupi-games/planetblupi/files/9999421/arabic.stories.zip)
Fixed.

**Comment by Skywalker13** [comment]
I'm ready for a release candidate, but now I'm "just" waiting on the code signing set for the Windows build...

I've just not added the voices because of https://github.com/blupi-games/planetblupi/issues/102#issuecomment-1120046039

**Comment by Skywalker13** [comment]
You can download a pre-release (for Windows) at this link: https://github.com/blupi-games/planetblupi-dev/releases/tag/v1.15.0-rc1

**Comment by Skywalker13** [comment]
Your work is ok for 1.15.0, I close the issue.. about the voices, I can add your sound if you improve a bit the quality (see https://github.com/blupi-games/planetblupi/issues/102#issuecomment-1120046039), feel free to reopen if you want

Thank you
