### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by elPatrixF** [blupi-games/planetblupi#103]
Hello! I'm currently working in a Spanish translation for Planet Blupi.
I've recorded almost all the voice lines, translated the UI elements, and I'm currently working on translating the stories.blp file.

To make it work I'd need to have some extra glyphs for the Spanish accents: (`áéíóú`), and also at least capital `Á` and capital `Ú` (preferrably all of them `ÁÉÍÓÚ`, but I haven't had the need to use all of them) and also `ñ`. Capital `Ñ` is technically also valid but theres _very_ few words that begin with ñ, like ñoqui (Gnocchi) so in practice we don't really need to waste a glyph with that here haha.

So, apart from `ü` for words like `pingüino`, the Spanish language doesn't use any other kind of new accent.
` á é í ó ú ñ ü Á É Í Ó Ú Ñ `

I'm latin american, but for general purposes it should just be listed as Spanish ("Español", `locale == "es"`), I've played this game since I was 7 and it would be great to finally be able to fulfill my dream of having this game be completely in Spanish!

**Comment by Skywalker13** [comment]
Hello

Thank you very much.. like with the Arabic translation, I need to find free time.. by the way, with Spanish is much simpler (for now) that Arabic.

**Comment by elPatrixF** [comment]
Thank you!
A small heads up, I am re-reading the _stories.blp_ translation and I've noticed some of them are inaccurate (Did it a long time ago for the original game) so I'm gonna be revising it again and posting an updated better quality version soon.

**Comment by elPatrixF** [comment]
I have revised the spanish stories.blp file.
I fixed all the typos (missing accents, and some choice of words)
Also realized I need glyphs for `¿` and `¡` (opening question mark and opening exclamation point). Those can just be the existing glyphs turned upside down!

[stories - (v2).blp](https://github.com/blupi-games/planetblupi/files/8934517/stories.-.v2.blp.txt)

**Comment by Skywalker13** [comment]
Hello, thank you

I think that I will try to replace the font sprites by SDL_ttf and I started to work on it. I've korean translations too and the sprite way is not possible anymore. When it's done, all languages will use SDL_ttf.

**Comment by Skywalker13** [comment]
I started to integrate your work. Because you have "hacked" the original game with the sprites, and now that I use SDL_ttf, you can write the right characters in the stories file (in UTF-8).

![image](https://user-images.githubusercontent.com/397862/198899074-68dc751e-974f-4274-ad7a-800e4ad04dc5.png)

**Comment by Skywalker13** [comment]
Example

![image](https://user-images.githubusercontent.com/397862/198899106-e145c1f7-f3d2-4f89-a030-62d489612ffa.png)

**Comment by elPatrixF** [comment]
Oh very nice! Should I recheck the files to use the right characters? Or are you using the older blp file instead of the last one i posted? Great work tho!

**Comment by Skywalker13** [comment]
I integrated the last one (v2) because it seems that you have improved the translations. I need just this file with the right (UTF-8) characters.

Thank you

**Comment by elPatrixF** [comment]
[stories.-.v2-UTF.blp](https://github.com/blupi-games/planetblupi/files/9896924/stories.-.v2-UTF.blp.txt)
Alright, would this one do the trick?

**Comment by Skywalker13** [comment]
It looks good

![image](https://user-images.githubusercontent.com/397862/198904493-c8cb83e1-8af4-4fb7-976d-e560369c0d79.png)

Thank you

**Comment by Skywalker13** [comment]
I'm ready for a release candidate, but now I'm "just" waiting on the code signing set for the Windows build...

**Comment by Skywalker13** [comment]
You can download a pre-release (for Windows) at this link: https://github.com/blupi-games/planetblupi-dev/releases/tag/v1.15.0-rc1
