### ISSUE TITLE
Mallet sound effect is a bit off when Blupi hits it downwards. The sticky trap also doesn't have a sound anymore.

### ISSUE THREAD

**Issue by omarogi35** [blupi-games/planetblupi#104]
So when Blupi is hitting the mallet downwards, (usually on teleporters and incubators) it makes the noise still, but it isn't as accurate as it used to be. Like when he hits it down twice in a row, the sound of the mallet can only be heard once instead of twice. I also noticed that the sticky trap doesn't make the sound effect when an enemy becomes trapped.

**Comment by Skywalker13** [comment]
Thanks for the report...

**Comment by Skywalker13** [comment]
I identified the regression; it's when I've replaced the whole DirectSound stuff by SDL_mixer. I decided to play a channel only if this channel was not already playing. Then, when a specific sound is longer that the animation, it's not stopped (rewarded) if the animation wants this sound again. The original implementation, just stop it and start again. I can restore this behaviour very easily.

**Comment by Skywalker13** [comment]
Mmmmh.. In the original it's a bit different.. the same problem appears when the speed is changed to 2x for example. It's not very good.. maybe I can improve it with a fade..

**Comment by Skywalker13** [comment]
I fixed the regression with the sticky trap.

**Comment by Skywalker13** [comment]
Now it's fine for the normal speed (1x). With the speed (2x) there are a lot of other problems because it's not possible to have something accurate in this case. At least, not with the current engine.

**Comment by omarogi35** [comment]
> 

Yeah, that's okay. 2x speed is different, it's way too fast for the sound to be accurate haha. Not a problem at all!
