### ISSUE TITLE
Speedy Blupi I and II

### ISSUE THREAD

**Issue by qsmodo** [blupi-games/planetblupi#105]
Could you please release the source code of Speedy Blupi I and II? (I tried to mail info@blupi.org but it was returned.)

**Comment by Skywalker13** [comment]
The mail is working as expected when I try to send something.

About Speedy Blupi, the sources are still not cleaned for open sourcing and it's not in the pipe for this year, and maybe not for the next. Sorry

**Comment by qsmodo** [comment]
I hope you can get to it next year.

Thanks for putting effort into open sourcing these games, such underrated gems from the 90s'.

**Comment by NonlinearFruit** [comment]
Also would love to compile Speedy Blupi from source some day. Keep up the good work!
