### ISSUE TITLE
With release build, the user missions are not saved properly in the user profile

### ISSUE THREAD

**Issue by Skywalker13** [blupi-games/planetblupi#11]
To reproduce, just edit a mission (release, not debug version), the mission is lost after rerun.

**Comment by JesseRoxII** [comment]
I had this problem too, but I fixed it. It only happens when the game is installed in C:/Program Files. Installing the game to a folder that needs admin permission will prevent world200.blp - world219.blp from being created. I installed it to C:/Users/(my name) and the editor worked.

**Comment by Skywalker13** [comment]
Yes it's because arounf 1997 (Windows 95 / 98) the security was a concept ignored by Microsoft).. Installing in an other directory is a workaround. The user mission must be saved elsewhere in the user profile.

**Comment by Skywalker13** [comment]
Fixed by https://github.com/blupi-games/planetblupi/commit/92d96d6ce2a7d52a0f6599fb87be5277df735b76
