### ISSUE TITLE
Debian package: Midi music doesn't work

### ISSUE THREAD

**Issue by OdyX** [blupi-games/planetblupi#113]
Although I'm sure I tested it back then, I can't get the planetblupi Debian package to play the MIDI files (when the midi package is installed, and --restore-midi is used).

![image](https://github.com/blupi-games/planetblupi/assets/417403/e879d4e3-20eb-442f-a429-99daae29dd30)

The select is blocked grey. Any clue would be nice!

**Comment by OdyX** [comment]
(btw, it's "choisis", not "choisi" )

**Comment by OdyX** [comment]
Scrap that… I was expecting music in the menu... It works in the game.

**Comment by Skywalker13** [comment]
> (btw, it's "choisis", not "choisi" )

Thanks, I change that for the next bugfix release
