### ISSUE TITLE
CMake doesn't handle missing static/shared libraries properly

### ISSUE THREAD

**Issue by krzys-h** [blupi-games/planetblupi#13]
I had only static SDL_kitchensink installed and was trying to make a shared build. CMake didn't detect any errors (it thought the library was present, but didn't even add the library to the linker), only the linker complained about missing symbols.
I don't have much experience with static builds in CMake, but I think it should report at least some kind of an error.

**Comment by krzys-h** [comment]
Also, now that you support dynamic-linking builds, maybe it would be a good idea to revert blupi-games/SDL_kitchensink@3f2c95367d91e5d51b7dc97c554025224a721438?

**Comment by Skywalker13** [comment]
Yes, of course, my bad... I've not really tested the shared linking. It was just for @OdyX which is using the official SDL_kitchensink repository for the Debian package.

**Comment by Skywalker13** [comment]
Should be ok
