### ISSUE TITLE
Running binary without data installed gives a weird error message

### ISSUE THREAD

**Issue by krzys-h** [blupi-games/planetblupi#15]
```
╭─krzys_h@krzysh-laptop ~/Pulpit/planetblupi-dev/planetblupi/cmake-build-debug  ‹master*› 
╰─➤  ./planetblupi 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stream error
[1]    24954 abort (core dumped)  ./planetblupi
```
It should probably be replaced with something like "Check your installation, data directory not found"

**Comment by Skywalker13** [comment]
Good catch, there is an SDL dialog for init errors.. It's a regression according to the old game (1997).

**Comment by Skywalker13** [comment]
Fixed by https://github.com/blupi-games/planetblupi/commit/eb044e13ca3c29093566c1f692474299e581a5de
