### ISSUE TITLE
Desktop file missing from shared build

### ISSUE THREAD

**Issue by OdyX** [blupi-games/planetblupi#34]
A .desktop file making good use of the icons would make Planet Blupi appear in XDG-compliant desktop environments.

I implemented one for Colobot with translation: 
* https://github.com/colobot/colobot/blob/407d8554669951be794788d37b268fb54bb67aec/desktop/colobot.desktop.in
* https://github.com/colobot/colobot/blob/407d8554669951be794788d37b268fb54bb67aec/desktop/CMakeLists.txt#L60
* https://github.com/colobot/colobot/blob/407d8554669951be794788d37b268fb54bb67aec/desktop/create_desktop_file.sh

**Comment by Skywalker13** [comment]
OK, mine is used only by the AppImage CMake stuff. I must investigate

**Comment by Skywalker13** [comment]
I added the english desktop file for usual builds (without planetblupi-dev) 29ad6c30f4ff1011097abb206457c5038839a67d
