### ISSUE TITLE
Suggestion: a better place to put the "no music" button

### ISSUE THREAD

**Issue by JesseRoxII** [blupi-games/planetblupi#43]
(I apologize if the "Issues" tab is the wrong place to post this. I'm new to GitHub, so I don't really know how it works yet.)

After adding the Music 10 button to the game, I saw that the No Music button had to be moved over because it didn't fit. In my opinion, the placement doesn't seem right, so here's my suggestion for a better place on the screen it should be.
To be specific, the sprite is 11 pixels to the right, and 110 pixels down. That way, it's similar to the placement of the Back button. (Yeah, I have OCD, lol.)
![](https://user-images.githubusercontent.com/27767153/32264532-6981d406-be9c-11e7-8da7-0e8ddb21c6fd.png)

**Comment by Skywalker13** [comment]
It's the right place, thanks for the suggestion

I will do that for the next minor version

**Comment by Skywalker13** [comment]
Fixed by 5a3b3eb
