### ISSUE TITLE
Dying while winning

### ISSUE THREAD

**Issue by jk314159** [blupi-games/planetblupi#53]
![image](https://user-images.githubusercontent.com/4022196/35982570-c3877138-0cb5-11e8-9801-1ce5c5d89c06.png)

In this situation, Blupi has enough energy to enter the house, but then dies. The player may win or lose the mission, and it seems to be random.

[Example mission](https://github.com/blupi-games/planetblupi/files/1707766/world200.zip)

**Comment by Skywalker13** [comment]
Funny

**Comment by Skywalker13** [comment]
Fixed by https://github.com/blupi-games/planetblupi/commit/e3d9377c424bc188bf97c861fe798fb3a1fa8c13
