### ISSUE TITLE
Invisible fire

### ISSUE THREAD

**Issue by jk314159** [blupi-games/planetblupi#54]
If fire is placed on nonflammable ground, it disappears but can still hurt Blupi.

In editor:
![image](https://user-images.githubusercontent.com/4022196/35983408-93fab0d6-0cb7-11e8-9c56-3e1044ccce42.png)

In mission:
![image](https://user-images.githubusercontent.com/4022196/35983413-9750e958-0cb7-11e8-9115-6a2301579893.png)
![image](https://user-images.githubusercontent.com/4022196/35983419-9a26c72e-0cb7-11e8-9d9d-8ffa4c5cf11b.png)

**Comment by Skywalker13** [comment]
It's in the "list" of funny bugs with the editor. If I fix, I think that I re-enable this bug with the `--restore-bugs` command ligne option.

Thanks for the report

**Comment by Skywalker13** [comment]
Fixed by https://github.com/blupi-games/planetblupi/commit/e7dd0ec7c753341ab51b8ccfdeed15de55b51f75

**Comment by Skywalker13** [comment]
My fix adds a regression : https://github.com/blupi-games/planetblupi-dev/issues/7
