### ISSUE TITLE
Enhancement: Allow right-click to delete objects in editor

### ISSUE THREAD

**Issue by jk314159** [blupi-games/planetblupi#55]
Currently, left-click and right-click do the same thing in the mission editor. Right-click should be able to delete objects of the selected type (ground, structures, or entities). Similar functionality is in Speedy Blupi, and would be useful here as well.

**Comment by Skywalker13** [comment]
Good idea, thanks

**Comment by Skywalker13** [comment]
Fixed by 403b5db
