### ISSUE TITLE
In construction 20, the game gets stuck on the victory screen

### ISSUE THREAD

**Issue by JesseRoxII** [blupi-games/planetblupi#56]
After winning construction level 20, it goes to the victory screen, but the button with the arrow doesn't do anything. So there's no way to leave that screen, and I have to Alt-F4 out of the game.

(This bug wasn't introduced in the new version, I remember it being in the game since v1.7.)

Also side note, "last002.png" is unused. Construction level 20 just uses "win.png" like all the others. But that doesn't really matter, because last002 and win are the same image anyway.

**Comment by Skywalker13** [comment]
Thank you for this report

**Comment by Skywalker13** [comment]
Fixed by https://github.com/blupi-games/planetblupi/commit/ef362c8b37618176edc7581b9ff743188693c18d
