### ISSUE TITLE
Unable to save a game

### ISSUE THREAD

**Issue by ido578** [blupi-games/planetblupi#57]
hi, 
I cant save the game in planet blupi

**Comment by Skywalker13** [comment]
Please, provide more informations otherwise it's useless for me.

Platform: Windows, Linux, Mac? and what version of the OS?
Game version?
Screenshot of the problem
What happens when trying to save? Crash? Other.. is the save entry shown or not in the save screen?
Any other useful informations...
Etc,...

**Comment by ido578** [comment]
ok thank you, I thought that you are aware of the problem that is why I didn't explain more about it, sorry. so-
platform: windows 10
game version: 1.12.4
while I'm playing the game, during a mission, theres a save button down the screen. when I click it, the screen goes to the saves screen and 10 slots of optional saves appears. when I click one of them, the screen goes back to the game and I can continue playing. then, when I go to the missions manu, there is a button down the screen that called "open another game" when I enter it - 10 free slots appeared, which mean I cant upload any saved game. 
I  hope I explained enough and waiting for your answer.

**Comment by Skywalker13** [comment]
Sorry for the delay... 

it seems that Planet Blupi is not able to save the files in your `%appdata%/Epsitec SA/Planet Blupi/data` directory. You should check the permissions on this directory.

**Comment by Skywalker13** [comment]
I close because it's the only report for this problem and it's a bit old now.
