### ISSUE TITLE
Add Turkish translations

### ISSUE THREAD

**Issue by Skywalker13** [blupi-games/planetblupi#75]

**Comment by punctdan** [comment]
Hi, I'm the one who did Turkish translations. I have the files but I don't know how to upload them here since it tells me that it doesn't support the file types. I'll put the link of files through Google Drive so you can get them. Here is the link:
https://drive.google.com/drive/folders/1H9Om8hq6zAeVrJUOmf9HWlV6FtQNOBL6?usp=sharing

These are the missing glyphs in the game:
Ç, ç, Ğ, ğ, İ, ı, Ö, ö, Ş, ş, Ü, ü (only "ç", "ö" and "ü" appears correctly when written in planetblupi.mo but all of them are replaced with a blank square when written in stories.blp)

**Comment by Skywalker13** [comment]
I uploaded a zip with your files, thank you

[drive-download-20190124T121900Z-001.zip](https://github.com/blupi-games/planetblupi/files/2791618/drive-download-20190124T121900Z-001.zip)

I work on this when I can (in my free time)

**Comment by Skywalker13** [comment]
The problem with the story file was just that yours is saved in a turkish encoding instead of UTF-8. Then I converted to UTF-8 and everything is ok. Now I'm drawing the missing glyphs.

**Comment by Skywalker13** [comment]
It's done, can I have your name for the website (in the translators section)? Are you interested by doing the Blupi voices? I will play with the pitch etc, ... in order to have a more cartoon sound.

**Comment by Skywalker13** [comment]
Here the README for the voices: README for the voices: https://github.com/blupi-games/planetblupi/blob/master/README.voices.md

**Comment by punctdan** [comment]
Thank you, I was going to ask about this.

**Comment by Skywalker13** [comment]
Hi @punctdan, I published a pre-release with your work, can you check a bit please? https://github.com/blupi-games/planetblupi-dev/releases/tag/v1.14.0-rc1

Thank you

**Comment by punctdan** [comment]
Everything looks good so far!

**Comment by Skywalker13** [comment]
Cool, thanks

**Comment by Skywalker13** [comment]
Hello, I decided to use "Planet Blupi" (no more translations for the title) with all languages (excepted for Hebrew)

Is my changes right please?
```diff
@@ -734,7 +734,7 @@ msgid "Quit"
 msgstr "Çık"
 
 msgid "Quit Planet Blupi"
-msgstr "Blupi Gezegeni'nden çık"
+msgstr "Planet Blupi'den çık"
 
 msgid "Quit construction"
 msgstr "Oyundan çık"
Stage this hunk [y,n,q,a,d,K,j,J,g,/,e,?]? y
@@ -948,7 +948,7 @@ msgid "You have failed, try again..."
 msgstr "Kaybettin, tekrar dene..."
 
 msgid "You have played Planet Blupi."
-msgstr "Blupi Gezegeni'ni oynadınız."
+msgstr "Planet Blupi'ni oynadınız."
 
 #, c-format
 msgid "construction %d, time %d"
```

**Comment by punctdan** [comment]
All of them are right except this part:

```
+msgstr "Planet Blupi'ni oynadınız."
```

It should be like this:

```
+msgstr "Planet Blupi'yi oynadınız."
```

**Comment by Skywalker13** [comment]
Thank you
