### ISSUE TITLE
Time bomb duplication

### ISSUE THREAD

**Issue by jummy0** [blupi-games/planetblupi#82]
[https://www.youtube.com/watch?v=VxIMPapq8ME](https://www.youtube.com/watch?v=VxIMPapq8ME)
If Blupi picks up a time bomb while it is counting down, he will be carrying a second time bomb. If this is done again to create a 3rd time bomb, the 3rd bomb cannot be used or picked up.

**Comment by Skywalker13** [comment]
good catch

**Comment by Skywalker13** [comment]
Fixed by f07d064cc9fc9edbbfa6e993152a1835118e8b3d
