### ISSUE TITLE
Game crash with dynamite in north or west corner

### ISSUE THREAD

**Issue by jummy0** [blupi-games/planetblupi#83]
[https://www.youtube.com/watch?v=mAW4Bawcvtk](https://www.youtube.com/watch?v=mAW4Bawcvtk)
If dynamite is blown up in the west corner of the map (1 tile beyond the visible area), the game will crash. If dynamite is blown up in the north corner, the game will crash when a menu is opened.

I assume, the game exceeds the limits of an array while deleting objects. This crash does not seem to happen in the south or east corners.

**Comment by Skywalker13** [comment]
I can't reproduce.. no crash for me

https://user-images.githubusercontent.com/397862/104785499-f015dc80-578a-11eb-995d-282d4c85503d.mp4

**Comment by jummy0** [comment]
There is one row of tiles in the black space.  The game will only crash when dynamite is placed in the black space.
In my video, the tooltip "Dynamite" appears when the mouse is in the black space.
![image](https://user-images.githubusercontent.com/4022196/104829760-7d653980-583c-11eb-8117-4530e6d4871f.png)

**Comment by Skywalker13** [comment]
Ok, the bug is with the map editor...

**Comment by jummy0** [comment]
I've found that the crash is due to an Access Violation, which is the same crash caused by out-of-bounds areas in versions 1.7 and 1.8 (right-clicking to send a Blupi out-of-bounds, or viewing a tooltip out-of-bounds).  Even if the map editor is fixed, it will not solve the root problem, which is that dynamite seems to lack bounds checking.
