### ISSUE TITLE
PAUSE key is not available on many keyboards

### ISSUE THREAD

**Issue by jummy0** [blupi-games/planetblupi#87]
The game can be paused using the PAUSE/BREAK key instead of ESC, which does not show the menu and allows the player to input commands to the Blupis. However, many keyboards (especially for laptops) do not have a PAUSE/BREAK key, and cannot pause this way.

The PAUSE command should be moved to a more common key, or be configurable.

**Comment by Skywalker13** [comment]
Laptop keyboards have always keys combinations for less common keys

**Comment by Skywalker13** [comment]
Witk thinkpad for example it's Fn+p

**Comment by jummy0** [comment]
Ah, I found it. On my laptop the combination is Fn+B.
