### ISSUE TITLE
Demo playback moves the mouse cursor when the window is unfocused

### ISSUE THREAD

**Issue by jummy0** [blupi-games/planetblupi#93]
If the game is left on the INIT screen and the demo starts, the user's mouse will be moved even if the window is unfocused.  This primarily affects Debug builds, as Release builds pause the game when focus is lost.

**Comment by Skywalker13** [comment]
Yes thanks, I'm aware of this behaviour. And like you have seen, it's not a problem with the Release build that's the reason why I've not changed that.

**Comment by Skywalker13** [comment]
OK, the bug is with the map editor...
