### ISSUE TITLE
[Enhancement] North is inconsistent

### ISSUE THREAD

**Issue by jummy0** [blupi-games/planetblupi#95]
In the code, "North" is diagonal, forward + right.
In the game, "North" is directly forward.

def.h : 106
![image](https://user-images.githubusercontent.com/4022196/106349998-3d6c7080-6298-11eb-833e-ab3be116fd01.png)

in game
![image](https://user-images.githubusercontent.com/4022196/106350034-64c33d80-6298-11eb-89ef-1265daceb092.png)

**Comment by Skywalker13** [comment]
IMHO it's two very different things.. the comments is for the code, to understand how it's designed.. the GUI is just for the gamer. It's fine that for the gamer the north is on top.
